### ISSUE TITLE
Using hs-probe in non rust projects. 

### ISSUE THREAD

**Issue by C47D** [probe-rs/hs-probe#15]
Hi,
I didn't searched a lot, is it possible to use this probe in non rust projects? Just signed up on the mailing list!

**Comment by Yatekii** [comment]
Hi!

Yes, this is 100% possible. We implement the CMSIS-DAP specification which is an open standard by ARM intended for SWD & J-Tag debugging.
So this probe will also work with Keil for example.

Great to hear!

**Comment by C47D** [comment]
Thanks for the information, looking forward to get an hs-probe!
