### ISSUE TITLE
5V Out

### ISSUE THREAD

**Issue by dbrgn** [probe-rs/hs-probe#5]
The JLink allows powering the target device through [pin 19 of the 20-pin connector](https://www.segger.com/products/debug-probes/j-link/technology/interface-description/) or [pin 7 of the 10-pin connector (opposite of TDI)](https://github.com/gfroerli/hardware-v2/blob/master/datasheets/ARM-JTAG-20-10_latest-schematic.pdf) (at least on the Olimex adapter. On other adapters, this pin is often unused and removed for keying). To enable this feature, you need to send the "power on" command to the debug probe first. You can chose between "power on" (temporarily enable 5V/USB power out until the probe is unplugged) or "power on perm" (permanently enable power on that pin).

It would be nice if the hs-probe would support this as well! I use that feature extensively, it saves a lot of time if I don't need a separate power supply.

**Comment by korken89** [comment]
In general I see no issue with this, but the STDC14 connector has GND on the KEY pin.
One could add a dual MOSFET to switch between GND or 5V.

Right now we have followed the STLinkV3 implementation and supply 5V on pin 1 of the STDC14 connector.

**Comment by korken89** [comment]
I fixed this for v1.3 :)

**Comment by dbrgn** [comment]
The hs-probe I got (v1.4) has the 5V output on the pin 7 of the STDC14, which is pin 5 of the 10-pin connector. However, for compatibility with JLink, Olimex etc it would need to be on pin 7 of the 10-pin connector (which is pin 9 of the STDC14).

Is this an accidental mix-up, or intentional?

To quote @adamgreig in Matrix:

> https://github.com/probe-rs/hs-probe/commit/37722db7d92eea28bd6c0161ef9d080652d21cef says it was done for "compatibility with tc2050" but I don't understand what that means

**Comment by korken89** [comment]
Hi, unfortunately this looks like an accidental mix-up :(
It should be on pin 9 on the STDC14 and pin 7 on the Cortex-M Debug connector.

"Luckily" the trace is reachable, so if one wants to use it properly a tiny cut and some soldering will solve it.

**Comment by dbrgn** [comment]
> "Luckily" the trace is reachable, so if one wants to use it properly a tiny cut and some soldering will solve it.

True, it should be pretty easy to cut in the upper left corner of the PCB (right next to the hole).

Afterwards I'd need to connect pin 3 of the MOSFET Q101 with pin 9 of the STDC14 connector, right? seems doable.

Once this is done, how is the 5V output enabled? Is there already support in the firmware?
