### ISSUE TITLE
[V1.1] It's impossible to use Tag Connect and debug connector at the same time

### ISSUE THREAD

**Issue by Disasm** [probe-rs/hs-probe#6]
50mil debug connector head is wide and overlaps with the Tag Connect footprint.

**Comment by Yatekii** [comment]
Ohh, good spot =) And yes, ofc, for writing the actual probe firmware, this is vital!

**Comment by korken89** [comment]
I have updated this locally, will push a fix soon :)

**Comment by korken89** [comment]
Fixed in 7cd8694384acd9bc7e83096ea85dd7931b26ae8c
